on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Test app
    runs-on: ubuntu-latest
    env:
      POSTGRES-USER: ci
      POSTGRES-PASSWORD: ci
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Cache Poetry
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-


      - name: Install dependencies
        run: poetry install --no-interaction --no-root
        env:
          POETRY_VIRTUALENVS_CREATE: false
      - run: docker compose up -d --build
      - run: pytest
        env:
          APP_URL: http://127.0.0.1:8002

      - run: docker compose logs app
        if: always()